# Generated by Django 6.0.7 on 2026-08-11 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0002_scholarship'),
    ]

    operations = [
        migrations.AddField(
            model_name='scholarship',
            name='amount',
            field=models.TextField(default='Not Specified'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='scholarship',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='scholarship',
            name='eligibility',
            field=models.TextField(),
        ),
    ]
